//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelAlbum.Web.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TravelAlbum.Web.App_GlobalResources.GlobalResources", typeof(GlobalResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание (bg).
        /// </summary>
        public static string BgDescriptionLabel {
            get {
                return ResourceManager.GetString("BgDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заглавие (bg).
        /// </summary>
        public static string BgTitleLabel {
            get {
                return ResourceManager.GetString("BgTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание (en).
        /// </summary>
        public static string EnDescriptionLabel {
            get {
                return ResourceManager.GetString("EnDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заглавие (en).
        /// </summary>
        public static string EnTitleLabel {
            get {
                return ResourceManager.GetString("EnTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добави снимка.
        /// </summary>
        public static string LabelAddSingleImage {
            get {
                return ResourceManager.GetString("LabelAddSingleImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добави пътуване.
        /// </summary>
        public static string LabelAddTravel {
            get {
                return ResourceManager.GetString("LabelAddTravel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Албум.
        /// </summary>
        public static string LabelAlbum {
            get {
                return ResourceManager.GetString("LabelAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Снимка 1.
        /// </summary>
        public static string UploadedImage_1 {
            get {
                return ResourceManager.GetString("UploadedImage_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Снимка 2.
        /// </summary>
        public static string UploadedImage_2 {
            get {
                return ResourceManager.GetString("UploadedImage_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Снимка 3.
        /// </summary>
        public static string UploadedImage_3 {
            get {
                return ResourceManager.GetString("UploadedImage_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Снимка 4.
        /// </summary>
        public static string UploadedImage_4 {
            get {
                return ResourceManager.GetString("UploadedImage_4", resourceCulture);
            }
        }
    }
}
